# Generated by Django 5.1.2 on 2024-10-17 13:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sumsub', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantmodel',
            name='applicant_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='applicantmodel',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('538b4a51-dcf6-47d3-9a09-48637dd13ce5'), primary_key=True, serialize=False),
        ),
    ]
