# Generated by Django 5.1.2 on 2024-10-17 13:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sumsub', '0002_alter_applicantmodel_applicant_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantmodel',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('94fe689c-a059-4f77-b3b2-624e1de0f755'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='applicantmodel',
            name='verification_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
